import Foundation

@main
struct GitVersionGenerator {
    static func main() throws {
        guard CommandLine.arguments.count == 6 else {
            FileHandle.standardError.write(Data("Usage: GitVersionGenerator <output-file> <github-sha> <github-ref-type> <github-ref-name> <github-head-ref>\n".utf8))
            exit(2)
        }

        let outputFile = URL(fileURLWithPath: CommandLine.arguments[1])
        let githubSHA = emptyStringAsNil(CommandLine.arguments[2])
        let githubRefType = emptyStringAsNil(CommandLine.arguments[3])
        let githubRefName = emptyStringAsNil(CommandLine.arguments[4])
        let githubHeadRef = emptyStringAsNil(CommandLine.arguments[5])

        let gitSHA = githubSHA ?? "unknown"
        let gitBranch = githubHeadRef ?? (githubRefType == "branch" ? githubRefName : nil)
        let gitTag = githubRefType == "tag" ? githubRefName : nil
        let contents = """
        // This file is generated by GitVersionPlugin. Do not edit.

        enum BuildInfo {
            static let gitSHA = \(String(reflecting: gitSHA))
            static let gitBranch: String? = \(swiftOptionalStringLiteral(gitBranch))
            static let gitTag: String? = \(swiftOptionalStringLiteral(gitTag))
        }

        """

        try FileManager.default.createDirectory(
            at: outputFile.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )

        if let existing = try? String(contentsOf: outputFile, encoding: .utf8), existing == contents {
            return
        }

        try contents.write(to: outputFile, atomically: true, encoding: .utf8)
    }

    private static func swiftOptionalStringLiteral(_ value: String?) -> String {
        guard let value else {
            return "nil"
        }
        return String(reflecting: value)
    }

    private static func emptyStringAsNil(_ value: String) -> String? {
        value.isEmpty ? nil : value
    }
}
