import Foundation
import Subprocess

@main
struct GitVersionGenerator {
    static func main() async throws {
        guard CommandLine.arguments.count == 3 else {
            FileHandle.standardError.write(Data("Usage: GitVersionGenerator <package-directory> <output-file>\n".utf8))
            exit(2)
        }

        let packageDirectory = CommandLine.arguments[1]
        let outputFile = URL(fileURLWithPath: CommandLine.arguments[2])
        let gitSHA = await currentGitSHA(packageDirectory: packageDirectory) ?? "unknown"
        let contents = """
        // This file is generated by GitVersionPlugin. Do not edit.

        enum BuildInfo {
            static let gitSHA = "\(gitSHA)"
        }

        """

        try FileManager.default.createDirectory(
            at: outputFile.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )

        if let existing = try? String(contentsOf: outputFile, encoding: .utf8), existing == contents {
            return
        }

        try contents.write(to: outputFile, atomically: true, encoding: .utf8)
    }

    private static func currentGitSHA(packageDirectory: String) async -> String? {
        do {
            let result = try await run(
                .name("git"),
                arguments: ["-C", packageDirectory, "rev-parse", "--verify", "HEAD"],
                output: .string(limit: 128),
                error: .discarded
            )

            guard result.terminationStatus.isSuccess else {
                return nil
            }

            return result.standardOutput?.trimmingCharacters(in: .whitespacesAndNewlines)
        } catch {
            return nil
        }
    }
}
