import Foundation
import Subprocess

@main
struct GitVersionGenerator {
    static func main() async throws {
        guard CommandLine.arguments.count == 7 else {
            FileHandle.standardError.write(Data("Usage: GitVersionGenerator <package-directory> <output-file> <github-sha> <github-ref-type> <github-ref-name> <github-head-ref>\n".utf8))
            exit(2)
        }

        let packageDirectory = CommandLine.arguments[1]
        let outputFile = URL(fileURLWithPath: CommandLine.arguments[2])
        let githubSHA = emptyStringAsNil(CommandLine.arguments[3])
        let githubRefType = emptyStringAsNil(CommandLine.arguments[4])
        let githubRefName = emptyStringAsNil(CommandLine.arguments[5])
        let githubHeadRef = emptyStringAsNil(CommandLine.arguments[6])

        let gitSHA: String
        if let githubSHA {
            gitSHA = githubSHA
        } else {
            gitSHA = await currentGitSHA(packageDirectory: packageDirectory) ?? "unknown"
        }

        let gitBranch: String?
        if let githubHeadRef {
            gitBranch = githubHeadRef
        } else if githubRefType == "branch" {
            gitBranch = githubRefName
        } else {
            gitBranch = await currentGitBranch(packageDirectory: packageDirectory)
        }

        let gitTag: String?
        if githubRefType == "tag" {
            gitTag = githubRefName
        } else {
            gitTag = await currentGitTag(packageDirectory: packageDirectory)
        }
        let contents = """
        // This file is generated by GitVersionPlugin. Do not edit.

        enum BuildInfo {
            static let gitSHA = \(String(reflecting: gitSHA))
            static let gitBranch: String? = \(swiftOptionalStringLiteral(gitBranch))
            static let gitTag: String? = \(swiftOptionalStringLiteral(gitTag))
        }

        """

        try FileManager.default.createDirectory(
            at: outputFile.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )

        if let existing = try? String(contentsOf: outputFile, encoding: .utf8), existing == contents {
            return
        }

        try contents.write(to: outputFile, atomically: true, encoding: .utf8)
    }

    private static func currentGitSHA(packageDirectory: String) async -> String? {
        await gitOutput(
            packageDirectory: packageDirectory,
            arguments: ["rev-parse", "--verify", "HEAD"],
            outputLimit: 128
        )
    }

    private static func currentGitBranch(packageDirectory: String) async -> String? {
        await gitOutput(
            packageDirectory: packageDirectory,
            arguments: ["symbolic-ref", "--quiet", "--short", "HEAD"],
            outputLimit: 512
        )
    }

    private static func currentGitTag(packageDirectory: String) async -> String? {
        let output = await gitOutput(
            packageDirectory: packageDirectory,
            arguments: ["tag", "--points-at", "HEAD", "--sort=refname"],
            outputLimit: 8 * 1024
        )

        return output?.split(whereSeparator: \.isNewline).first.map(String.init)
    }

    private static func gitOutput(packageDirectory: String, arguments: [String], outputLimit: Int) async -> String? {
        do {
            let result = try await run(
                .name("git"),
                arguments: Arguments(["-C", packageDirectory] + arguments),
                output: .string(limit: outputLimit),
                error: .discarded
            )

            guard result.terminationStatus.isSuccess else {
                return nil
            }

            let output = result.standardOutput?.trimmingCharacters(in: .whitespacesAndNewlines)
            return output?.isEmpty == false ? output : nil
        } catch {
            return nil
        }
    }

    private static func swiftOptionalStringLiteral(_ value: String?) -> String {
        guard let value else {
            return "nil"
        }
        return String(reflecting: value)
    }

    private static func emptyStringAsNil(_ value: String) -> String? {
        value.isEmpty ? nil : value
    }
}
