name: Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  cache_version: 2

jobs:
  linux:
    runs-on: ubuntu-22.04
    container: ubuntu:jammy
    name: Docker on Ubuntu
    steps:
    - name: Install Docker
      run: apt-get update && apt-get -qq -y install docker docker-compose
    - name: Build Docker Image
      run: docker-compose build
    - name: Run Docker Image
      run: docker-compose up -d open-meteo
